version: 2.1
orbs:
  node: circleci/node@7.2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "24.11.1"
          install-yarn: true
      - run:
          command: node --version
          name: Check Node Version
      - run:
          command: yarn -v
          name: Check Yarn Version
      - run:
          command: yarn
          name: Install Dependencies
      - run:
          command: yarn build
          name: Build Project
      - persist_to_workspace:
          root: ~/project
          paths: .

workflows:
  build-and-deploy-workflow:
    jobs:
      - build