version: 2.1
orbs:
  node: circleci/node@7.2.1
  github-pages-orb: fernfernfern/github-pages-orb@0.0.10
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "24.11.1"
          install-yarn: true
      - run:
          command: npm install -g corepack
          name: Install Corepack
      - run:
          command: |
            corepack enable
            corepack prepare yarn@4.12.0 --activate
            yarn -v
          name: Install and Verify Yarn
      - run:
          command: yarn
          name: Install Dependencies
      - run:
          command: yarn build
          name: Build Project
      - persist_to_workspace:
          root: ~/project
          paths: .
  deploy:
    executor: github-pages-orb/default
    steps:
      - attach_workspace:
          at: ~/project
      - github-pages-orb/deploy:
          build-dir: dist

workflows:
  build-and-deploy-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main