version: 2.1
orbs:
  node: circleci/node@7.2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "24.11.1"
          install-yarn: true
      - run:
          command: npm install -g corepack
          name: Install Corepack
      - run:
          command: |
            corepack enable
            corepack prepare yarn@4.12.0 --activate
            yarn -v
          name: Install and Verify Yarn
      - run:
          command: yarn
          name: Install Dependencies
      - run:
          command: yarn build
          name: Build Project
      - persist_to_workspace:
          root: ~/project
          paths: .
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "circleci@example.com"
            git config --global user.name "CircleCI Job"

            cd dist
            
            git config --global init.defaultBranch main
            git init
            git add .
            git commit -m "Deploy from CircleCI [skip ci]"
            
            git push --force https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git main:gh-pages

workflows:
  build-and-deploy-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main